### ISSUE TITLE
Access to the FHIR Server UI (wrong access point)

### ISSUE THREAD

**Issue by malakhovks** [grongierisc/Swift-FHIR-Iris#2]
Hello!
I try to test your project.
I can't access to FHIR Server UI access point that you mention:

> At the end of the building process you will be able to connect to the FHIR repository :
    http://localhost:32783/fhir/portal/patientlist.html

There is an error in your manual.
According to [IRIS FHIR Portal](https://github.com/diashenrique/iris-fhir-portal) repo the FHIR Server UI access point is: 
http://localhost:32783/csp/user/fhirUI/patientlist.html

**Comment by grongierisc** [comment]
You are right but I change the endpoint here : https://github.com/grongierisc/Swift-FHIR-Iris/blob/08634d1f5730dc86a2548b5c76be7928a76f34e9/module.xml#L11

For the more, I use Henrique FHIR portal code but it was modified to handle some unique case I have with the step count.

I commited few fixes, like do not use iris key, and stop iris quietly, let me kno if that solve your problem

**Comment by malakhovks** [comment]
> You are right but I change the endpoint here :
> 
> https://github.com/grongierisc/Swift-FHIR-Iris/blob/08634d1f5730dc86a2548b5c76be7928a76f34e9/module.xml#L11
> 
> For the more, I use Henrique FHIR portal code but it was modified to handle some unique case I have with the step count.
> 
> I commited few fixes, like do not use iris key, and stop iris quietly, let me kno if that solve your problem

I used docker-compose.yml from your project, but I can't access via http://localhost:32783/fhir/portal/patientlist.html

Okay I will check

**Comment by grongierisc** [comment]
what is you host machine ?
make sure, you pull the last commit.
can you provide logs of : 
```sh
docker-compose build --no-cache --progress plain
```
and log of the iris container : 
```sh
docker logs --tail 1000 -f <container id>
```

**Comment by malakhovks** [comment]
> what is you host machine ? make sure, you pull the last commit. can you provide logs of :
> 
> ```shell
> docker-compose build --no-cache --progress plain
> ```
> 
> and log of the iris container :
> 
> ```shell
> docker logs --tail 1000 -f <container id>
> ```

Okay I will try with your latest commit and let you know

**Comment by malakhovks** [comment]
Fixed.
Thanks!
